
    alias s='g "/Users/jay/sup" '
    export s="/Users/jay/sup"
    alias A='g "/Users/jay" '
    export A="/Users/jay"
    alias ew='g "/Users/jay/eclipse_workspace" '
    export ew="/Users/jay/eclipse_workspace"
    alias sss='g "/Users/jay/sss" '
    export sss="/Users/jay/sss"
    alias sss='g "/Users/jay/sss" '
    export sss="/Users/jay/sss"
    alias apps='g "/Applications" '
    export apps="/Applications"
    alias appvim='g "/Applications/MacVim.app/Contents/MacOS" '
    export appvim="/Applications/MacVim.app/Contents/MacOS"
    alias vrun='g "/Applications/MacVim.app/Contents/Resources/vim/runtime" '
    export vrun="/Applications/MacVim.app/Contents/Resources/vim/runtime"
    alias j='g "/Users/jay" '
    export j="/Users/jay"
    alias tf='g "/Users/jay/trueframe" '
    export tf="/Users/jay/trueframe"
    alias tfr='g "/Users/jay/trueframe/_Jay/jay/_trueframe/jay/resume" '
    export tfr="/Users/jay/trueframe/_Jay/jay/_trueframe/jay/resume"
    alias down='g "/Users/jay/Downloads" '
    export down="/Users/jay/Downloads"
    alias tftop='g "/Users/jay/trueframe/_Jay/jay/_trueframe" '
    export tftop="/Users/jay/trueframe/_Jay/jay/_trueframe"
    alias tfindex='g "/Users/jay/trueframe/_Jay/jay/_trueframe/jay" '
    export tfindex="/Users/jay/trueframe/_Jay/jay/_trueframe/jay"
    alias xx='g "/j/diag/xx" '
    export xx="/j/diag/xx"
    alias xy='g "/j/diag/xy" '
    export xy="/j/diag/xy"
    alias doc='g "/Users/jay/Documents" '
    export doc="/Users/jay/Documents"
    alias dev='g "/Users/jay/Development" '
    export dev="/Users/jay/Development"
    alias t2='g "/Users/jay/Documents/workspace2/Timer2" '
    export t2="/Users/jay/Documents/workspace2/Timer2"
    alias BAP='g "/Users/jay/backup/android_projects" '
    export BAP="/Users/jay/backup/android_projects"
    alias sdk='g "/Users/jay/Development/adt-bundle-mac-x86_64-20140702/sdk" '
    export sdk="/Users/jay/Development/adt-bundle-mac-x86_64-20140702/sdk"
    alias sdktools='g "/Users/jay/Development/adt-bundle-mac-x86_64-20140702/sdk/platform-tools" '
    export sdktools="/Users/jay/Development/adt-bundle-mac-x86_64-20140702/sdk/platform-tools"
    alias eclipse='g "/Users/jay/Development/adt-bundle-mac-x86_64-20140702" '
    export eclipse="/Users/jay/Development/adt-bundle-mac-x86_64-20140702"
    alias pic='g "/Users/jay/Pictures" '
    export pic="/Users/jay/Pictures"
    alias sup='g "/Users/jay/sup" '
    export sup="/Users/jay/sup"
    alias igd='g "/Users/jay/neon_workspace/io.gunter.demo" '
    export igd="/Users/jay/neon_workspace/io.gunter.demo"
    alias bounce='g "/Users/jay/test/js/bounce" '
    export bounce="/Users/jay/test/js/bounce"
    alias demo='g "/Users/jay/neon_workspace/io.gunter.demo/src/io/gunter/demo" '
    export demo="/Users/jay/neon_workspace/io.gunter.demo/src/io/gunter/demo"
    alias hh3='g "/Users/jay/hadoop/hadoop-3.0.0" '
    export hh3="/Users/jay/hadoop/hadoop-3.0.0"
    alias hh2='g "/Users/jay/hadoop/hadoop-2.7.5" '
    export hh2="/Users/jay/hadoop/hadoop-2.7.5"
    alias rq6='g "/Users/jay/js/react-quickly/ch6" '
    export rq6="/Users/jay/js/react-quickly/ch6"
    alias rq6='g "/Users/jay/js/react-quickly/ch06" '
    export rq6="/Users/jay/js/react-quickly/ch06"
    alias rq3='g "/Users/jay/js/react-quickly/ch03" '
    export rq3="/Users/jay/js/react-quickly/ch03"
    alias rq9='g "/Users/jay/js/react-quickly/ch09" '
    export rq9="/Users/jay/js/react-quickly/ch09"
    alias rq10='g "/Users/jay/js/react-quickly/ch10/tooltip" '
    export rq10="/Users/jay/js/react-quickly/ch10/tooltip"
    alias bq='g "/Users/jay/js/react/bounce_rq" '
    export bq="/Users/jay/js/react/bounce_rq"
    alias rqew='g "/Users/jay/js/react-quickly/ch12/email-webpack" '
    export rqew="/Users/jay/js/react-quickly/ch12/email-webpack"
    alias rg='g "/Users/jay/js/react/gunter.io" '
    export rg="/Users/jay/js/react/gunter.io"
    alias roapp='g "/Users/jay/repos/redorbit-api-develop/app" '
    export roapp="/Users/jay/repos/redorbit-api-develop/app"
    alias roapi='g "/Users/jay/repos/redorbit-api-develop/app/api" '
    export roapi="/Users/jay/repos/redorbit-api-develop/app/api"
    alias rdaas='g "/Users/jay/repos/RDaaS-ui-develop" '
    export rdaas="/Users/jay/repos/RDaaS-ui-develop"
    alias stud='g "/Users/jay/repos/pipeline-studio-develop" '
    export stud="/Users/jay/repos/pipeline-studio-develop"
    alias stub='g "/Users/jay/repos/pipeline-studio-backend" '
    export stub="/Users/jay/repos/pipeline-studio-backend"
    alias studp='g "/Users/jay/repos/pipeline-studio-develop/src/components/app/projects" '
    export studp="/Users/jay/repos/pipeline-studio-develop/src/components/app/projects"
    alias studs='g "/Users/jay/repos/pipeline-studio-develop/src" '
    export studs="/Users/jay/repos/pipeline-studio-develop/src"
    alias studsc='g "/Users/jay/repos/pipeline-studio-develop/src/components" '
    export studsc="/Users/jay/repos/pipeline-studio-develop/src/components"
    alias studsca='g "/Users/jay/repos/pipeline-studio-develop/src/components/app" '
    export studsca="/Users/jay/repos/pipeline-studio-develop/src/components/app"
    alias studscc='g "/Users/jay/repos/pipeline-studio-develop/src/components/common" '
    export studscc="/Users/jay/repos/pipeline-studio-develop/src/components/common"
    alias duxs='g "/Users/jay/repos/redux/src" '
    export duxs="/Users/jay/repos/redux/src"
    alias duxx='g "/Users/jay/repos/redux/examples" '
    export duxx="/Users/jay/repos/redux/examples"
    alias des='g "/Users/jay/studio_design" '
    export des="/Users/jay/studio_design"
    alias me='g "/Users/jay/js/cytoscape/menus+edges" '
    export me="/Users/jay/js/cytoscape/menus+edges"
    alias studpd='g "/Users/jay/repos/pipeline-studio-develop/src/components/app/projects/projectDetails" '
    export studpd="/Users/jay/repos/pipeline-studio-develop/src/components/app/projects/projectDetails"
    alias qp='g "/Users/jay/repos/pipeline-studio-develop/src/queries/pipeline" '
    export qp="/Users/jay/repos/pipeline-studio-develop/src/queries/pipeline"
    alias sam='g "/Users/jay/studio_design/SamplePipelines" '
    export sam="/Users/jay/studio_design/SamplePipelines"
    alias tt='g "/Users/jay/test" '
    export tt="/Users/jay/test"
    alias qj='g "/Users/jay/repos/pipeline-studio-develop/src/queries/project" '
    export qj="/Users/jay/repos/pipeline-studio-develop/src/queries/project"
    alias ds='g "/Users/jay/repos/pipeline-studio-develop/src" '
    export ds="/Users/jay/repos/pipeline-studio-develop/src"
    alias dscc='g "/Users/jay/repos/pipeline-studio-develop/src/components/common" '
    export dscc="/Users/jay/repos/pipeline-studio-develop/src/components/common"
    alias dp='g "/Users/jay/repos/pipeline-studio-develop/src/components/app/projects" '
    export dp="/Users/jay/repos/pipeline-studio-develop/src/components/app/projects"
    alias back='g "/Users/jay/backups" '
    export back="/Users/jay/backups"
    alias kubia='g "/Users/jay/test/docker/http" '
    export kubia="/Users/jay/test/docker/http"
    alias ewt='g "/Users/jay/sss/java" '
    export ewt="/Users/jay/sss/java"
    alias giolc='g "/Users/jay/gunter.io/public_html/test/life-clock" '
    export giolc="/Users/jay/gunter.io/public_html/test/life-clock"
